[package]
name = "sample-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
libsample = { path = "../lib" }
clap = { version = "3.1.0", features = ["cargo"] }

[[bin]]
name = "sample-tool"
path = "src/main.rs"
